### ISSUE TITLE
Close button is selected when user opens the settings form

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#100]
![image](https://user-images.githubusercontent.com/42398485/49686655-3df48c80-fabd-11e8-94c3-d33cd20ffdda.png)

1. Deploy the App and Open (Theme: Dark)
2. Select Settings

**Actual:** Close button is selected when user opens the settings form

**Expected:** Should not select the close button 

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by ksmacleod99** [comment]
closing, since we have another ticket to remove it
