### ISSUE TITLE
Settings icon in the menu selected when the end-user closes the form

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#102]
![image](https://user-images.githubusercontent.com/42398485/49686690-d985fd00-fabd-11e8-96e1-c1061161202d.png)

1. Deploy the App and Open (Theme: Dark)
2. Click Settings
3. Close the Settings

**Actual:** Settings icon in the menu is selected when the end-user closes the form out

**Expected:** It is not necessary to select the icon

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by ksmacleod99** [comment]
duplicate of #85
