### ISSUE TITLE
[$20] Validation message Ordered Set value of row 1 cannot be empty is not shown

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#104]
![image](https://user-images.githubusercontent.com/42398485/49686786-506fc580-fabf-11e8-94c4-b0523bee9311.png)

1. Deploy the App and Open (Theme: Dark)
2. Select Ordered Set from the list
3. Click Add new value
4. Delete the existing value
5. Click Add and you will get Ordered Set value of row 1 cannot be empty
6. Click Cancel
7. Click Add new value
8. Add another two empty values
9. Add value to the first item
10. Delete all the items in the form
11. Click Add

**Actual:** Validation message is not shown

**Expected:** Should display the same validation message - Ordered Set value of row 1 cannot be empty

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by mhikeo** [comment]
@ksmacleod99 I'm disabling the Add button if Ordered Set is empty.

**Comment by nahidshahin** [comment]
@ksmacleod99 @mhikeo getting null pointer exception at 
`src/app/components/add-value-dialog/add-value-dialog.component.html:33` (as `data.values.orderedValues` is null for `hash maps`)

![screenshot 2018-12-29 at 4 40 54 pm](https://user-images.githubusercontent.com/1224995/50537371-caf4a800-0b88-11e9-80ae-16aeb04209d2.png)
