### ISSUE TITLE
[$15]  No delete confirmation message shown after deleting a redis server

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#107]
![image](https://user-images.githubusercontent.com/42398485/49687445-6635b880-fac8-11e8-8c71-ff4f5a997d18.png)

1. Deploy the App and Open
2. Create few redis servers
3. Delete a redis server

**Actual:** No delete confirmation message shown after deleting a redis server

**Expected:** Should display a confirmation message

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by ksmacleod99** [comment]
Please see my question on your PR regarding the merge conflict.

**Comment by phead** [comment]
Hi, @ksmacleod99 

Is this fix accepted ? I found my MR has been merged.
