### ISSUE TITLE
[$15] Wrong message displayed after deleting a redis server

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#108]
![image](https://user-images.githubusercontent.com/42398485/49687468-b3198f00-fac8-11e8-9b02-1394b9d95dcf.png)

1. Deploy the App and Open
2. Create few redis servers
3. Delete a redis server
4. Don't select any redis server and click delete button
5. Select and delete a redis server

**Actual:** you need select Redis instance first

**Expected:** Should display a confirmation message

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by phead** [comment]
Hi, please check this: https://github.com/topcoderinc/TC-redis-manager/pull/176
