### ISSUE TITLE
[$20] First redis command is shown when user open the redis cli

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#110]
![image](https://user-images.githubusercontent.com/42398485/49687519-a9445b80-fac9-11e8-9949-b79b55136349.png)

1. Deploy the App and Open
2. Create few redis servers
3. Select a redis server
4. Enter some redis command to the cli
5. Collase the cli
6. Expand it

**Actual:** first redis command is shown when user open the redis cli

**Expected:** Should display the last commend

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by afrisalyp** [comment]
https://github.com/topcoderinc/TC-redis-manager/pull/183
