### ISSUE TITLE
[$20] Refresh + Expand All nodes option is enabled

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#111]
![image](https://user-images.githubusercontent.com/42398485/49687555-28399400-faca-11e8-83ad-62e431b90e40.png)

1. Deploy the App and Open
2. Create few redis servers
3. Delete a redis server
4. Click more
5. Click Refresh + Expand All
6. Select a redis server
7. Click Refresh + Expand All

**Actual:** Even though user didn't selects a redis server Refresh + Expand All nodes option is enabled

**Expected:** Should disable the Refresh + Expand All nodes option

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by nahidshahin** [comment]
PR https://github.com/topcoderinc/TC-redis-manager/pull/159
