### ISSUE TITLE
[common] table needs to support sorting by column header

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#114]
1. open the app, select 'default-local', expanded all nodes

2. click on 'global-ordered-list', add some new values, click on column headers (e.g. Value, Score), observe

expected: needs to support sorting by column headers.

actual: see screenshot, no such feature.

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browsers: Latest Firefox

**Comment by winterflame** [comment]
![sorting](https://user-images.githubusercontent.com/4590317/49697493-fc65fd80-fbf2-11e8-885b-8a30254a5d12.jpg)

**Comment by standlove** [comment]
this is not supported by redis
