### ISSUE TITLE
Application is not working on Internet Explorer 11

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#115]
![image](https://user-images.githubusercontent.com/42398485/49699184-c47b9d80-fb93-11e8-83b4-b1fa3bd11032.png)

1. Deploy the App and open

**Actual:** Application is not working on Internet Explorer 11

**Expected:** Application should work on ie 11

**Browser(s):** Internet Explorer 11 (Windows)

**Comment by ksmacleod99** [comment]
thank you for testing in IE! Our client does not use it, so I will be closing the issue.
