### ISSUE TITLE
[$25] All redis commands are shown despite the selected redis server

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#119]
![image](https://user-images.githubusercontent.com/42398485/49701525-2b5c7f00-fbb3-11e8-8acb-3458742dd4b2.png)

1. Deploy the App and open (theme: Dark)
2. Select a redis server
3. Click redis command and enter: redis
4. Select another redis server

**Actual:** All redis commands are shown despite the selected redis server. That means all the commands are mixed.

**Expected:** Should show the redis commands belongs to server only

**Browser(s):** MS Edge (Windows)

**Comment by ksmacleod99** [comment]
Ideally, commands should persist when user switches back and forth unless explicitly cleared.

**Comment by ksmacleod99** [comment]
hey there @mhikeo there is a merge conflict on your PR. I think a rebase might fix it. Could you please investigate? Thank you!

**Comment by mhikeo** [comment]
@ksmacleod99 I have updated the PR. Kindly check.
