### ISSUE TITLE
[$5] (common) capitalization should be consistent

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#12]
### Reproduction Steps ###

1. open the app

2. observe the tooltips of each button, and text on the buttons.

### Expected Result ###

1) Add new Value-> Add New Value
2) remove this redis Server -> Remove This Redis Server
3) Add new redis Server -> Add New Redis Server
etc.

### Actual Result ###

*See screenshots.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![r1](https://user-images.githubusercontent.com/4590317/49592850-2c23c400-f9ad-11e8-8165-025bc8194ea6.jpg)

![r2](https://user-images.githubusercontent.com/4590317/49592853-2cbc5a80-f9ad-11e8-9f6c-9bca4bba4ad7.jpg)

![r3](https://user-images.githubusercontent.com/4590317/49592884-3b0a7680-f9ad-11e8-84b2-597930ae8d5c.jpg)

**Comment by Schpotsky** [comment]
fixed in #154
