### ISSUE TITLE
[$5] Small gap on the menu

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#122]
![image](https://user-images.githubusercontent.com/42398485/49710421-de9e9580-fbfe-11e8-8a01-8067dfe92cc1.png)

1. Deploy the App and open (theme: Dark)
2. Select a redis server
3. You can see a small gap after the more menu

**Actual:** Small gap on the menu

**Expected:** Should not display such a gap

**Browser(s):** Google Chrome 71 (Windows)

**Comment by nahidshahin** [comment]
PR https://github.com/topcoderinc/TC-redis-manager/pull/142
