### ISSUE TITLE
[$20] Redis server removes even though it is not selected

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#123]
https://monosnap.com/file/kzm6dogU6FIbeZAKfDlq1QZuLkNCtZ

1. Deploy the App and open (theme: Dark)
2. Create a redis server - localhost-2(localhost:6379:0)
3. Create a redis server - localhost-3(localhost:6379:0)
4. Select redis server - localhost-3(localhost:6379:0)
5. Click Disconnect (Redis server selection removed)
6. Click Delete
7. Click Yes

**Actual:** After disconnecting; if the redis server is still selected, Should display the color in gray and also the details should be shown on the right side panel. So after disconnecting redis server is not selected, but as soon as user press delete, that disconnected redis server removes from the list

**Expected:** Redis server should not remove from the list and should display a validation message - you need select Redis instance first

**Browser(s):** Google Chrome 71 (Windows)

**Comment by ksmacleod99** [comment]
Possibly related to #61.
