### ISSUE TITLE
[$10] Help page shows two scroll bars

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#125]
![image](https://user-images.githubusercontent.com/42398485/49711640-2117a080-fc06-11e8-8baa-e6ca80686b29.png)

1. Deploy the App and open (theme: Dark)
2. Click Help
3. Expand a section

**Actual:** Help page shows two scroll bars

**Expected:** Should display one

**Browser(s):** Google Chrome 71 (Windows)

**Comment by iversonLv** [comment]
can't reproduce this issue at Version 71.0.3578.98 (Official Build) (64-bit)
