### ISSUE TITLE
[$15] ordered set should support double value for Score

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#128]
1. open the app, click on 'default-local' 

2. click on Add new Records

3. select value type as Ordered Set, enter "os" for Key, "helloworld" for Value, 10.88 for Score, save it

4. click to view saved values

expected: should support storing double value

actual: see screenshots.

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browsers: *Safari Version 12.0 (14606.1.36.1.9)*

![os](https://user-images.githubusercontent.com/4590317/49717299-9f6d5480-fc91-11e8-8301-159d520b6da2.jpg)

![os2](https://user-images.githubusercontent.com/4590317/49717301-9f6d5480-fc91-11e8-8951-6f95c3e3893e.jpg)

**Comment by phead** [comment]
![image](https://user-images.githubusercontent.com/1858410/50378828-277e3180-0676-11e9-96c6-59e4f4144ad1.png)

Hi, please check the mr:  https://github.com/topcoderinc/TC-redis-manager/pull/174

**Comment by ksmacleod99** [comment]
hey @phead I'm still unable to add decimal values for the score. Any thoughts?

**Comment by phead** [comment]
OK, I'll check it soon.

**Comment by phead** [comment]
Hi, @ksmacleod99 

Please check the MR here : https://github.com/topcoderinc/TC-redis-manager/pull/224
