### ISSUE TITLE
After end-user deletes the entire list (List, Set, Ordered List) table view is still shown

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#129]
![image](https://user-images.githubusercontent.com/42398485/49736023-9a3ae600-fc4e-11e8-8686-f70b99c8ce8c.png)

1. Deploy the App and open (theme: Dark)
2. Click on a redis sever
3. Create List, Set or Ordered lIST
4. Delete all the items on the list

**Actual:** After end-user deletes the entire list (List, Set, Ordered List) table view is still shown

**Expected:** Should hide the table view

**Browser(s):** Google Chrome 71 (Windows)

**Comment by ksmacleod99** [comment]
I imagine this is because the list is still created, just empty. We will have to check and see what the desired behavior is.
