### ISSUE TITLE
[$10] Continuous loading icon displayed after deleting all the item in a property

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#132]
![image](https://user-images.githubusercontent.com/42398485/49807247-3502f580-fd1f-11e8-92d7-fdfc1a69c009.png)

1. Deploy the App and open
2. Click on a redis sever
3. Create List, Set or Ordered lIST
4. Delete all the items on the list

**Actual:** Continuous loading icon displayed after deleting all the item in a property

**Expected:** Loading icon should remove

**Browser(s):** Firefox (Windows)

**Comment by ksmacleod99** [comment]
I was only able to replicate this on an ordered list after deleting list items.

**Comment by phead** [comment]
Hi,
Please check merge request: https://github.com/topcoderinc/TC-redis-manager/tree/issue/phead/132
