### ISSUE TITLE
[$30] pagination does not work

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#18]
### Reproduction Steps ###

1. open the app

2. click on "global-ordered-list"

3. click on Next page, observe

### Expected Result ###

pagination should work.

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![p](https://user-images.githubusercontent.com/4590317/49684309-70c67100-fb0d-11e8-9af2-e76c765d558f.jpg)

**Comment by ksmacleod99** [comment]
See #80 for more specific steps.
