### ISSUE TITLE
[$10] Not sure the use of checkboxes

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#20]
### Reproduction Steps ###

1. open the app

2. click on "global-ordered-list"

3. select some rows using checkbox

### Expected Result ###

Should allow to perform further operation by selecting them.
### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![d](https://user-images.githubusercontent.com/4590317/49686003-daa04400-fb28-11e8-96b5-7376162ffca6.jpg)


Suggestion: Move "Delete Key" button into the table so that the user will understand they can click that.

**Comment by iversonLv** [comment]
I think the screenshot is wrong?
