### ISSUE TITLE
[$5] Actions should be Action

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#21]
### Reproduction Steps ###

1. open the app

2. click on "global-ordered-list"

### Expected Result ###

Actions should be Action, since there is only one action.

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by phead** [comment]
Hi,

Please check merge request: https://github.com/topcoderinc/TC-redis-manager/pull/136
