### ISSUE TITLE
[$10] [common] validation error modal is too far away

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#22]
### Reproduction Steps ###

1. open the app

2. expand all items on left, click on "name", edit it to empty, click Save

### Expected Result ###

validation error modal should not be that far away.

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![far](https://user-images.githubusercontent.com/4590317/49684783-9787a600-fb13-11e8-8617-3d55f37721d1.jpg)

**Comment by iversonLv** [comment]
That is a material snack-bar that is usually located at the bottom, it's not a modal
https://material.angular.io/components/snack-bar/overview
