### ISSUE TITLE
(common) Actions inconsistent on record types

### ISSUE THREAD

**Issue by ksmacleod99** [topcoderinc/TC-redis-manager#226]
Action availability is generally inconsistent among the record types. 
String record type not listed, as it is very different from the rest.
Observe: 
![ordered-set](https://user-images.githubusercontent.com/28678836/50739230-22a79a80-11ab-11e9-9153-8dfa6a61d841.png)
![list](https://user-images.githubusercontent.com/28678836/50739231-22a79a80-11ab-11e9-8835-a75ba8b0362e.png)
![set](https://user-images.githubusercontent.com/28678836/50739232-23403100-11ab-11e9-93e7-f3c23e16026e.png)
![hash-map](https://user-images.githubusercontent.com/28678836/50739233-23403100-11ab-11e9-9611-c0002f313208.png)

Recommendations: 
all record types have edit and delete actions per line item
all line items have a selection box
buttons up top are for bulk editing/deleting

**Comment by standlove** [comment]
Redis list and set cannot delete/edit the middle element in redis. so we cannot add same actions as map
