### ISSUE TITLE
[$5] Because of the color used for Add new value text; it is barely visible

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#23]
1. Deploy the App and Open
2. Select an item from the right view
3. Click Add new Records
4. Add a new value (Value Type: Hash-Map)
5. Check the color of the Add new value text

**Actual:** Because of the color used for Add new value text; it is barely visible

**Expected:** Should use a darker color

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by ksmacleod99** [comment]
Related to issue #10

**Comment by nahidshahin** [comment]
PR https://github.com/topcoderinc/TC-redis-manager/pull/157 solves `Add new value`. But the button is disabled at `Edit value` modal. So it the fade color is expected. Right?
