### ISSUE TITLE
should not show scroll bar if items per page is 10

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#237]
### Reproduction Steps ###

1. open the app

2. observe the table, scroll up/down

### Expected Result ###

should not show scroll bar if items per page is 10

### Actual Result ###

*See screenshot*
### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

**Comment by winterflame** [comment]
![sc](https://user-images.githubusercontent.com/4590317/51007850-290b8d00-1584-11e9-8721-65c9529ae5d1.jpg)

**Comment by standlove** [comment]
won't fix.
