### ISSUE TITLE
[common] style of confirmation popup is different from the validation popup

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#238]
### Reproduction Steps ###

1. open the app

2. play with the app, make it show some confirmation popup by disconnecting the server

3. try to create an empty key/value, observe

### Expected Result ###

style should be consistent

### Actual Result ###

*See screenshot*
### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

**Comment by winterflame** [comment]
![e1](https://user-images.githubusercontent.com/4590317/51008147-7d633c80-1585-11e9-8953-103db6976a2f.jpg)
![e2](https://user-images.githubusercontent.com/4590317/51008148-7d633c80-1585-11e9-94bf-5c43dbb58107.jpg)

**Comment by standlove** [comment]
won't fix
