### ISSUE TITLE
[$5] (common) "OK" and "Ok" on validation error modal should be consistent

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#24]
### Reproduction Steps ###

1. open the app

2. expand all items on left, click on "name", edit it to empty, click Save, observe

3. click "+", then leave Name empty, click Add, observe

### Expected Result ###

"OK" and "Ok" on validation error modal should be consistent

### Actual Result ###

*See screenshots.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![ok](https://user-images.githubusercontent.com/4590317/49684841-69ef2c80-fb14-11e8-96bc-25609ccf876d.jpg)

![far](https://user-images.githubusercontent.com/4590317/49684849-7c696600-fb14-11e8-91f8-62592d3ea8c9.jpg)

**Comment by winterflame** [comment]
Also , the message should be consistent. Currently, one is "String value cannot be empty", the other is "Value cannot be empty".

**Comment by phead** [comment]
Hi, Please check https://github.com/topcoderinc/TC-redis-manager/pull/150
