### ISSUE TITLE
table column should be moved to right side a bit

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#240]
### Reproduction Steps ###

1. open the app

2. click user:1:role to see the table

### Expected Result ###

column should be moved to right side a bit

### Actual Result ###

*See screenshot*
### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

**Comment by winterflame** [comment]
![space](https://user-images.githubusercontent.com/4590317/51008216-cf0bc700-1585-11e9-935f-745553fcaa53.jpg)

**Comment by standlove** [comment]
won't fix.
