### ISSUE TITLE
user can edit value even though the modal still displayed on the screen

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#241]
### Reproduction Steps ###

1. open the app

2. expand the nodes, click on BasicUser:1:id

3. edit the value, click Save

4. when the modal is still shown, edit the value again

### Expected Result ###

should not allow user to edit if the modal still shown

### Actual Result ###

*See screenshot*
### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

**Comment by winterflame** [comment]
![edit](https://user-images.githubusercontent.com/4590317/50978591-b8d31c00-152f-11e9-9532-613b67b77549.jpg)

**Comment by standlove** [comment]
won't fix.
