### ISSUE TITLE
space too large between text and the bottom line

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#242]
### Reproduction Steps ###

1. open the app

2. expand the nodes, click on BasicUser:1:id

3. observe the value and its bottom line

### Expected Result ###

should decrease the distance

### Actual Result ###

*See screenshot*
### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

**Comment by winterflame** [comment]
![spaces](https://user-images.githubusercontent.com/4590317/51008259-08443700-1586-11e9-950c-89d0b1e78d46.jpg)

**Comment by standlove** [comment]
it's a text-area. Won't fix.
