### ISSUE TITLE
Can't edit key value

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#247]
![image](https://user-images.githubusercontent.com/42398485/50979404-02821f00-14bc-11e9-8b71-e620f77884e9.png)

1. Deploy the App and run the application
2. Expand the redis sever
3. Create a Hash Map with several items
4. Select an item and click edit
5. Edit key

**Actual:** Can't edit key value

**Expected:** Should be able to edit the key values

**Comment by standlove** [comment]
No. This is expected.
