### ISSUE TITLE
[$5] buttons on confirmation modal should be center aligned

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#25]
### Reproduction Steps ###

1. open the app

2. expand all items on left

3. click on "productTyes:["device""software"]"", click Delete Branch button

### Expected Result ###

buttons on confirmation modal should be center aligned

### Actual Result ###

*See screenshots.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![cen](https://user-images.githubusercontent.com/4590317/49685982-90b75e00-fb28-11e8-9d73-49f40b72351d.jpg)

This is a common issue for other popup modals.

**Comment by nahidshahin** [comment]
PR https://github.com/topcoderinc/TC-redis-manager/pull/153
