### ISSUE TITLE
Select all icon difference in two pages

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#250]
![image](https://user-images.githubusercontent.com/42398485/50979882-14b08d00-14bd-11e9-9984-aed625764d14.png)
![image](https://user-images.githubusercontent.com/42398485/50979911-2003b880-14bd-11e9-9c72-9223726d147e.png)

1. Deploy the App and run the application
2. Expand the redis sever
3. Create a Ordered Set with 25 items
4. Select the items per page to 10
5. Click select all from the first page
6. Move to the second page to check the select all icon style (Check-mark)
7. Move to the third page to check the select all icon style (hyphen)

**Actual:** Select all icon difference in two pages

**Expected:** Should be display as a hyphen

**Comment by standlove** [comment]
you must deselect some rows.
