### ISSUE TITLE
no max limit for string in a set

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#254]
### Reproduction Steps ###

1. open the app

2. click global-set-01

3. add a new value with super long text, observe

### Expected Result ###

should set max limit for string

### Actual Result ###

*See screenshot*
### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Latest Firefox*

**Comment by winterflame** [comment]
![long](https://user-images.githubusercontent.com/4590317/51008605-7a694b80-1587-11e9-9702-17d248c5d31f.jpg)

**Comment by standlove** [comment]
redis doesn't have restriction for string length.
