### ISSUE TITLE
font style should be consistent

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#256]
### Reproduction Steps ###

1. open the app

2. click global-string

3. observe

### Expected Result ###

font style should be consistent

### Actual Result ###

*See screenshot*
### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Latest Firefox*

**Comment by winterflame** [comment]
![font](https://user-images.githubusercontent.com/4590317/50981320-ae1b8580-1535-11e9-8c52-66fcc357b093.jpg)

**Comment by standlove** [comment]
Ok.
