### ISSUE TITLE
[$5] typo on confirmation modal

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#26]
### Reproduction Steps ###

1. open the app

2. expand all items on left

3. click on a key "name", click Delete Key button

### Expected Result ###

belongs to -> belong to

### Actual Result ###

*See screenshots.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![belong](https://user-images.githubusercontent.com/4590317/49594767-8d4d9680-f9b1-11e8-943e-1983da8b35ba.jpg)

**Comment by nahidshahin** [comment]
PR https://github.com/topcoderinc/TC-redis-manager/pull/148
