### ISSUE TITLE
no validation message if adding duplicate values (after trimming) to a set

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#261]
### Reproduction Steps ###

1. open the app

2. click default-local

3. click Add New Records

4. select Value Type as Set

5. enter key name properly, then add one more row, enter "abc" and " abc " respectively

6. save the input, observe

### Expected Result ###

should show validation error that there are duplicate values.

### Actual Result ###

*See screenshot*
### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Latest Firefox*

**Comment by winterflame** [comment]
https://monosnap.com/file/n2lTQiTFwTVm9Vqoad8yQ4XLnBzszj

**Comment by standlove** [comment]
no need to trim the key / values.
