### ISSUE TITLE
Common - No maximum limit for value fields in the application

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#263]
![image](https://user-images.githubusercontent.com/42398485/50982619-34e34a80-14c3-11e9-9001-e2a72c07568f.png)

1. Deploy the App and run the application
2. Expand the redis sever and select it
3. Click add new record and select any value type
4. Enter long value
4. Click add

**Actual:** No maximum limit for value fields in the application

**Expected:** Should set a maximum characters limit for the value field

**Browser(s):** Google Chrome 71.0.3578.98 (Windows)

**Comment by standlove** [comment]
Redis doesn't have this restriction.
