### ISSUE TITLE
Empty string can be saved

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#266]
![image](https://user-images.githubusercontent.com/42398485/50985464-fe5cfe00-14c9-11e9-9cdf-85c03f3188a6.png)

1. Deploy the App and run the application
2. Expand the redis sever and select it
3. Select a string key
4. Delete the value and click on the save button and you will get a validation message
5. Click on abother key type from the list appeared on the left side of the screen
6. Click on the same string value

**Actual:** Empty string can be saved when user removes the string from the field

**Expected:** Application should not allow empty string

**Browser(s):** Google Chrome 71.0.3578.98 (Windows)

**Comment by standlove** [comment]
duplicated with #267
