### ISSUE TITLE
Import values are not displayed/if the values are incorrect should display an error message

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#268]
![image](https://user-images.githubusercontent.com/42398485/50991057-65ce7a00-14d9-11e9-9241-81e82128c8a6.png)

1. Deploy the App and run the application
2. Expand the redis sever and select it
3. Click sub-menu and import
4. Enter some random value
5. Unchecked flush BD
6. Click import

**Actual:** Import values are not displayed

**Expected:** Should display imported value to the list or if the values are incorrect should display an error message

**Browser(s):** Google Chrome 71.0.3578.98 (Windows)

**Comment by standlove** [comment]
I don't follow, I believe a toast message will be displayed after you click "Import". 
And as the command is invalid, nothing will be imported.

**Comment by codejamtc** [comment]
@standlove Invalid commands are triggered and after that empty redis server is displayed. There is an error message but it quickly disappears but if the commands are invalid system should not allow to trigger them.

https://www.screencast.com/t/GfYiAe6X5eb

**Comment by standlove** [comment]
You have Flush DB checked in your screencast. 

Redis is not a database, we cannot rollback.
