### ISSUE TITLE
[$5] typo on success modal

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#27]
### Reproduction Steps ###

1. open the app

2. expand all items on left

3. click on a key "name", click Delete Key button, confirm the delete

### Expected Result ###

delete successful -> delete successfully

### Actual Result ###

*See screenshots.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![del](https://user-images.githubusercontent.com/4590317/49594750-86bf1f00-f9b1-11e8-80f7-2c4b3338bf0c.jpg)

**Comment by nahidshahin** [comment]
PR https://github.com/topcoderinc/TC-redis-manager/pull/146
