### ISSUE TITLE
Can add multi-line values and the layout arrangement is also not good

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#270]
![image](https://user-images.githubusercontent.com/42398485/50995582-1e4deb00-14e5-11e9-820d-a86f3805c4ea.png)

1. Deploy the App and run the application
2. Expand the redis sever and select it
3. Select a Hash Map and click add new value
4. Enter a key and add multi-line values

**Actual:** Can add multi-line values and the layout arrangement is also not good

**Expected:** All the other value fields are not accepting multi-line values

**Browser(s):** Google Chrome 71.0.3578.98 (Windows)

**Comment by standlove** [comment]
won't fix.
