### ISSUE TITLE
Item arrangement within the branch changes

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#272]
![image](https://user-images.githubusercontent.com/42398485/51001816-e6e83a00-14f6-11e9-9586-badb81f85c02.png)

1. Deploy the App and run the application
2. Selects a redis server and click add new records
3. Enter key=global-config:config1
4. Enter a value and click add
5. create 4-5 items
6. Add a new item global-config:config7 and refresh the list and it will appear at the bottom of the list
7. Add a new item global-config:config  8 and refresh the list and it will appear as the first item of the list

**Actual:** Item arrangement within the branch changes when user enters a differently

**Expected:** Should arrange the items in correct order

**Browser(s):** Google Chrome 71.0.3578.98 (Windows)

**Comment by standlove** [comment]
you are right.
