### ISSUE TITLE
Empty key name is created

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#273]
![image](https://user-images.githubusercontent.com/42398485/51001888-2878e500-14f7-11e9-84c7-d92c7fc01c20.png)

1. Deploy the App and run the application
2. Selects a redis server and click add new records
3. Enter key=global-config:
4. Enter a value and click add

**Actual:** Empty key name is created

**Expected:** Should not allow any empty key name values

**Browser(s):** Google Chrome 71.0.3578.98 (Windows)

**Comment by standlove** [comment]
This is the group feature handled by the front-end. The key in redis is just "global-config:" actually. 

We should probably validate there are characters before and after `:`.

**Comment by standlove** [comment]
After a second thought, I prefer not to validate this. `::` is a valid part of the key, and it's better not disallow simply because it looks strange on our UI.
