### ISSUE TITLE
Should display a meaningful message when user tries to export invalid redis server data

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#278]
![image](https://user-images.githubusercontent.com/42398485/51007063-a810af00-150b-11e9-9097-481121b2e61e.png)

1. Deploy the App and run the application
2. Click +
3. Create a redis server with port 6355
4. Click export and select that redis server
5. Click export

**Actual:** Fail to export redis commands: unknown error

**Expected:** Fail to export redis commands: Redis instance not exist

**Browser(s):** Google Chrome 71.0.3578.98 (Windows)

**Comment by standlove** [comment]
we will fix #281 instead.

**Comment by standlove** [comment]
A valid connection can become invalid. So this should still be fixed ...

**Comment by standlove** [comment]
duplicated with #308
