### ISSUE TITLE
Refresh and expand all nodes will not work

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#279]
![image](https://user-images.githubusercontent.com/42398485/51007141-02117480-150c-11e9-96af-6c6d4fc2b075.png)

1. Deploy the App and run the application
2. Click +
3. Create a redis server with port 6355
4. Create a redis server with port 6379
4. Click Refresh + Expand All Nodes

**Actual:** Refresh and expand all nodes will not work

**Expected:** Should expand the working redis server nodes

**Browser(s):** Google Chrome 71.0.3578.98 (Windows)

**Comment by standlove** [comment]
It will only expand the selected node.
