### ISSUE TITLE
Empty branches can be created

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#282]
![image](https://user-images.githubusercontent.com/42398485/51008107-f32cc100-150f-11e9-8ad1-d129b5477f13.png)

1. Deploy the App and run the application
2. Select a redis server
3. Click add new record
4. Set key=global-config-qa:Test:Test::config-1 and value=1
4. Click Add

**Actual:** Empty branches can be created

**Expected:** Should validate the double ::

**Browser(s):** Google Chrome 71.0.3578.98 (Windows)

**Comment by standlove** [comment]
It's duplicated with #273
