### ISSUE TITLE
all data missing after import action

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#283]
### Reproduction Steps ###

1. open the app

2. click More > Import

3. enter "ab" as Value, click Import

### Expected Result ###
Should not empty the data if import action is performed unsuccessfully.

### Actual Result ###

*See screencast.*
### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Latest Firefox*

**Comment by winterflame** [comment]
https://monosnap.com/file/Rmv260uKIs002HZ4u3WPWAhrDyOhWn

**Comment by standlove** [comment]
Because the "FLUSH DB" is checked, which will clear the database.
