### ISSUE TITLE
import modal is not easy to follow (better to make some enhancement)

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#285]
### Reproduction Steps ###

1. open the app

2. click More > Import, observe the modal

### Expected Result ###
Should be easy for new user to follow how to import.
e.g. change the commands list to a description paragraph like:
Supported commands: command1, command2, etc.
Then give an example for any command below that.

### Actual Result ###

*See screenshot, user does not know how to proceed (how to fill the value field).*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Latest Firefox*

**Comment by winterflame** [comment]
![import](https://user-images.githubusercontent.com/4590317/51011977-cb803c00-1595-11e9-96e6-e14022007f08.jpg)

**Comment by standlove** [comment]
won't fix
