### ISSUE TITLE
user does not know what rows failed while importing

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#286]
### Reproduction Steps ###

1. open the app

2. click More > Import

3. use attached file to import, observe the error modal

### Expected Result ###
User should be able to know which rows failed.

### Actual Result ###

*See screenshot, user only knows the amount of failed rows.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Latest Firefox*

**Comment by winterflame** [comment]
[sampleImport.txt](https://github.com/topcoderinc/TC-redis-manager/files/2747998/sampleImport.txt)

**Comment by winterflame** [comment]
![f](https://user-images.githubusercontent.com/4590317/51012074-4ea19200-1596-11e9-990c-db70258a3b9c.jpg)

**Comment by standlove** [comment]
we have don't have places to show that much info.
