### ISSUE TITLE
clicking on the "App Theme" label should not pop up the dropdown list

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#287]
### Reproduction Steps ###

1. open the app

2. click on the Settings icon

3. then click on the "App Theme" label, observe

### Expected Result ###

Clicking on the "App Theme" label should not pop up the dropdown list. The dropdown list should only be triggered by clicking on itself.

### Actual Result ###

*See screenshot, it will popup the dropdown list.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 64.0.2 (64-bit)*

**Comment by winterflame** [comment]
![app](https://user-images.githubusercontent.com/4590317/51017942-c5e41f80-15b0-11e9-93a6-0f517dbc3244.jpg)

**Comment by winterflame** [comment]
![a2](https://user-images.githubusercontent.com/4590317/51017963-e2805780-15b0-11e9-839f-ffe36797ba4d.jpg)

**Comment by standlove** [comment]
won't fix.
