### ISSUE TITLE
page flickers when entering redis command in the cli panel

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#288]
### Reproduction Steps ###

1. open the app

2. toggle Cli panel

3. enter some command to execute, observe the page

### Expected Result ###

page should not flicker.

### Actual Result ###

*See screenshot or screencast.*

### Screenshots or screencast ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 64.0.2 (64-bit)*

**Comment by winterflame** [comment]
https://monosnap.com/file/eId3eN46cjbwgAwXk0xrB5megBckes

**Comment by standlove** [comment]
Yes, if the data on the UI is affected, the new data should be reloaded.

**Comment by kinfkong** [comment]
Yes, you are right. However the current refresh doesn't work, check:
https://monosnap.com/file/sdMjNLx4UZSA2ywjiSEa7RTVL9Wkbg
maybe this is related another bug.

**Comment by standlove** [comment]
yes, there is another bug for this. I will close this.
