### ISSUE TITLE
better disallow user to enter non digit for Port

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#289]
### Reproduction Steps ###

1. open the app

2. click the + button

3. enter non digit for Port

### Expected Result ###

better disallow user to enter non digit for Port.

### Actual Result ###

*See screenshot or screencast.*

### Screenshots or screencast ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 64.0.2 (64-bit)*

**Comment by winterflame** [comment]
![port](https://user-images.githubusercontent.com/4590317/51020751-7145a200-15ba-11e9-913b-57e8a1651021.jpg)

**Comment by standlove** [comment]
That's the default firefox behaviour for number input.
