### ISSUE TITLE
[$15] should not allow special chars for Key

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#29]
### Reproduction Steps ###

1. open the app

2. click "localhost" > Add new Records

3. then enter some special chars for Key , and random text for value, save that

### Expected Result ###

should validate the Key properly

### Actual Result ###

*See screenshots.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![k](https://user-images.githubusercontent.com/4590317/49685860-acba0000-fb26-11e8-8299-9e5b73f62f13.jpg)

**Comment by afrisalyp** [comment]
Redis accepts all characters for keys.
https://redis.io/topics/data-types-intro

@ksmacleod99 Should we limit the keys for special characters?

**Comment by ksmacleod99** [comment]
Hi there, I apologize for not getting back sooner. No, let's leave the special characters. I'll close this issue.
