### ISSUE TITLE
data is not sorted by key in the table for hmset

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#290]
### Reproduction Steps ###

1. open the app

2. click global-map

3. observe the table

### Expected Result ###

Data should be sorted by key alphabetically in the table.

### Actual Result ###

*See screenshot, it looks like randomly shown.*

### Screenshots or screencast ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 64.0.2 (64-bit)*

**Comment by winterflame** [comment]
![mp](https://user-images.githubusercontent.com/4590317/51021292-18770900-15bc-11e9-83ca-3071213fa880.jpg)

**Comment by standlove** [comment]
won't fix.
