### ISSUE TITLE
"OK" button can be removed from the toast message if it is automatically dismissed

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#291]
### Reproduction Steps ###

1. open the app

2. click global-map

3. click Edit, observe

### Expected Result ###

"OK" button can be removed from the toast message if it is automatically dismissed.

### Actual Result ###

*See screenshot.*

### Screenshots or screencast ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 64.0.2 (64-bit)*

**Comment by winterflame** [comment]
![toast](https://user-images.githubusercontent.com/4590317/51021452-87ecf880-15bc-11e9-92ba-a82b531e4fd4.jpg)

**Comment by standlove** [comment]
won't fix.
