### ISSUE TITLE
User unable to see cursor position in light theme

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#295]
Steps to Reproduce

1. Add a server to the deployed app.
2. Try editing the server name
3. Cursor position is not seen in light theme.

Actual Result

User unable to see the cursor position in light theme.

Expected Result

User should be able to see cursor position in light theme,

Frequency : 5/5

Device: Laptop

OS : Windows 7

Browser: Chrome (latest)

Images

![cursor](https://user-images.githubusercontent.com/13567734/51051330-868df100-15f9-11e9-9116-bceec27c58a4.jpg)

**Comment by standlove** [comment]
duplicated with #236
