### ISSUE TITLE
Suggestion to load the home page of app by clicking logo

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#296]
Steps to Reproduce

1. Add a server to the deployed app.
2. Click on the logo of the app.
3. Suggest to display the home page of app.

Actual Result

Not displaying the home page of app.

Expected Result

Suggest to display the home page of app.

Frequency : 5/5

Device: Laptop

OS : Windows 7

Browser: Chrome (latest)

Images

![cursor](https://user-images.githubusercontent.com/13567734/51051556-20ee3480-15fa-11e9-9d96-2a832cadfb8e.jpg)

**Comment by Jacob15** [comment]
![logo](https://user-images.githubusercontent.com/13567734/51051596-42e7b700-15fa-11e9-8742-8fcaeff78c9d.jpg)

**Comment by standlove** [comment]
No
