### ISSUE TITLE
Help document HELP text to be placed at the top left corner with good format.

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#299]
Steps to Reproduce

1. open the deployed app.
2. Open the Help link.
3. Help text in the start of the document to be verified.

Actual Result

Help text is not in the start of the document.

Expected Result

User should see Help text in the top left corner with good formatting.

Frequency : 5/5

Device: Laptop

OS : Windows 7

Browser: Chrome (latest)

Images

![helpcontent](https://user-images.githubusercontent.com/13567734/51052593-2600b300-15fd-11e9-9a49-192c0e5e9f56.jpg)

**Comment by kinfkong** [comment]
I do not understand this. It looks like the "Help" is already in the top left corner?
What need to fix this?
Thanks.

**Comment by Jacob15** [comment]
@kinfkong Its to be placed in the most left of the UI. Looks like its not so left aligned to the modal. 

Thanks

**Comment by standlove** [comment]
this issue seems trivial. let's just close it.
