### ISSUE TITLE
Settings form app theme color changed when selecting magenta.

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#301]
Steps to Reproduce

Steps to Reproduce

1. Deploy the app.
2. Click on the Settings link.
3. Change the color to Magenta
4. Now close the Settings form.
5. Open the settings form again.
6.  Observe the color of App theme.
7. Its in white color instead of Magenta unlike other themes.

Actual Result

Color of App theme text is not Magenta.

Expected Result

Color of App theme text is not Magenta.

Frequency : 5/5

Device: Laptop

OS : Windows 7

Browser: Chrome (latest)

Images

![apptheme](https://user-images.githubusercontent.com/13567734/51053754-91984f80-1600-11e9-8a81-e106d56045ea.jpg)

**Comment by standlove** [comment]
won't fix.
