### ISSUE TITLE
Settings and more icons getting moved when user moves the panel right side.

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#305]
Steps to Reproduce

1. Deploy the app.
2. Enter some values in the Enter Redis command.
3. Drag the left panel to right side.
4. observe the settings and more icon is getting moved.

Actual Result

User able to see settings and more icon getting moved.

Expected Result

User should not able to make settings and more icon getting moved along with panel.

Frequency : 5/5

Device: Laptop

OS : Windows 7 32 bit

Browser: Chrome (latest)

Images

![menu](https://user-images.githubusercontent.com/13567734/51068256-9df0cc80-1641-11e9-8bc2-9636c1e8e7de.jpg)

**Comment by standlove** [comment]
won't fix.
