### ISSUE TITLE
Suggestion to remove light app theme due to user usability issues,

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#307]
Steps to Reproduce

1. Deploy the app.
2. Change the App theme to light.
3. Observe the User interface.
4. Its not much usability to the user. (cursor position is not shown anywhere)

Actual Result

Usability issues with the app in light theme.

Expected Result

Light theme should be much user interface to the user.

Frequency : 5/5

Device: Laptop

OS : Windows 7

Browser: Chrome (latest)

Images

![ux](https://user-images.githubusercontent.com/13567734/51068481-ba423880-1644-11e9-9705-71fbdb5e7b26.jpg)

**Comment by standlove** [comment]
No.
