### ISSUE TITLE
Previous redis command is displayed even though user disabled all the servers

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#311]
![image](https://user-images.githubusercontent.com/42398485/51068646-c39cb800-15e6-11e9-9224-8ec69de0afcd.png)

1. Deploy the App and run the application
2. Create 5 redis servers with different names
3. Select a server and click on the redis command cli
4. enter a command and collapse it
5. Select another redis server
6. Disconnect that server

**Actual:** Previous redis command is displayed even though user disabled all the servers and also when user selects another redis server from the list

**Expected:** Should clear the command and display the 'Please select a redis instance to enter redis command'

**Browser(s):** Firefox 64.0.2 (Windows)

**Comment by standlove** [comment]
won't fix
