### ISSUE TITLE
HSET HM 4 4-Edited command result returns 0 instead 1

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#314]
![image](https://user-images.githubusercontent.com/42398485/51069323-22b3fa00-15f2-11e9-8b61-cb242b9858ee.png)

1. Deploy the App and run the application
2. Select a server and Create a Hash Map
3. Click on the redis command cli
4. Type: HSET HM 4 4-Edited  - https://redis.io/commands/HDEL
4. Click Enter

**Actual:** 0

**Expected:** 1

**Browser(s):** Firefox 64.0.2 (Windows)

**Comment by standlove** [comment]
It's because the key `4` already exists in Map.
