### ISSUE TITLE
Item arrangement is incorrect

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#315]
![image](https://user-images.githubusercontent.com/42398485/51074040-608b3f80-163f-11e9-9a05-856d715bdd89.png)

1. Deploy the App and run the application
2. Select a server and create a SET
3. Click on the redis command CLI
4. Type: SADD myset one two three four five six seven eight nine ten

**Actual:** one two three four five six seven eight nine ten

**Expected:** eight one six three five seven two four ten nine

**Browser(s):** Firefox 64.0.2 (Windows)

**Comment by standlove** [comment]
SET has no order.
