### ISSUE TITLE
[$5] "X" button on Settings modal should be removed for consistency

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#32]
### Reproduction Steps ###

1. open the app

2. click Settings button

### Expected Result ###

"X" button on Settings modal should be removed for consistency.

### Actual Result ###

*See screenshots.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![x](https://user-images.githubusercontent.com/4590317/49595571-3ba60b80-f9b3-11e8-8388-101d4da28e99.jpg)

**Comment by ksmacleod99** [comment]
I think we need to keep the 'x'; I am going to go ahead and approve this for your work, but will close that PR.
