### ISSUE TITLE
[Safari] the position of the increase/decrease icon changed while focusing in it

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#321]
### Reproduction Steps ###

1. open the app

2. click the "+" button

3. focus the Port field, observe

### Expected Result ###

the position of the icon should not change.

### Actual Result ###

*See screenshot.*

### Screenshots or screencast ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Safari 12.0*

**Comment by winterflame** [comment]
Focused:
![focused](https://user-images.githubusercontent.com/4590317/51075368-6461a500-16c5-11e9-8a54-1501d04c94cd.jpg)

Not focused:
![notfocused](https://user-images.githubusercontent.com/4590317/51075373-73485780-16c5-11e9-9cfe-40aa70e97268.jpg)

**Comment by sumitdaga** [comment]
i think this is a problem with angular material on safari itself, you can try opening material input type number on safari and i couldn't find anything on their repo or anywhere else about this  
not sure if this can be fixed!

**Comment by standlove** [comment]
Ok.
