### ISSUE TITLE
User can't delete a value from the bulk-edit form

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#33]
1. Deploy the App and Open
2. Select an item from the right view
3. Click Add new Records
4. Add a new value (Value Type: Hash-Map)
5. Add few records to the list
6. Select three values from the table
7. Click Edit button
8. Click delete button

**Actual:** After opening the bulk-edit form, if user click on the delete button, it won't work

**Expected:** Should able to delete the value

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by JDK88** [comment]
You mean delete the line in the redis 
OR
only do not show in the dialog (when update , the key/value will be not affected).
@codejamtc

**Comment by JDK88** [comment]
https://github.com/topcoderinc/TC-redis-manager/pull/211
@codejamtc

**Comment by ksmacleod99** [comment]
hey there @JDK88 I'm sorry I'm just now seeing your question after testing! We would like the delete buttons in the dialogue to delete the items off of the redis instance. Would you be able to update this for me?

**Comment by JDK88** [comment]
![image](https://user-images.githubusercontent.com/26185691/50500452-5c322480-0a8c-11e9-91a6-81ed681aa468.png)

The latest version in master branch, cannot show the edit dialog on My mac...
@ksmacleod99

**Comment by ksmacleod99** [comment]
something else I merged broke it 😩

**Comment by JDK88** [comment]
Sorry, "delete the line in the redis" should change so much code than I expected.
And I think the UI will be confused for me.
