### ISSUE TITLE
All the texts should starts with a upper case letters

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#337]
![image](https://user-images.githubusercontent.com/42398485/51080236-6d3e8080-169d-11e9-84b7-f31a0279bca5.png)

![image](https://user-images.githubusercontent.com/42398485/51080239-7af40600-169d-11e9-9d02-18ad0968b6b5.png)

![image](https://user-images.githubusercontent.com/42398485/51080244-87785e80-169d-11e9-885f-3cc9e15c5845.png)

1. Deploy the App and run the application
2. Select a server

**Actual:** Text start with a lower case letter

**Expected:** All the texts should starts with a upper case letter

**Browser(s):** Firefox 64.0.2 (Windows)

**Comment by standlove** [comment]
won't fix
