### ISSUE TITLE
[$5] (common) "Delete Confirm" should be "Delete Confirmation"

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#34]
### Reproduction Steps ###

1. open the app

2. click on "localhost" > "global-ordered-list"

3. click "Delete Key"

### Expected Result ###

"Delete Confirm" should be "Delete Confirmation"

### Actual Result ###

*See screenshots.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![dc](https://user-images.githubusercontent.com/4590317/49595707-8c1d6900-f9b3-11e8-9687-baf8f4b62c76.jpg)

**Comment by phead** [comment]
Hi,
Please check this: https://github.com/topcoderinc/TC-redis-manager/pull/145
