### ISSUE TITLE
Fail to connect redis server message

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#340]
Steps to reproduce

1. deploy using docker installed in Vbox.
2. After docker run start the instance using http://<vboxhost>: port(used in docker run)
3. Application loaded but redis server failed to start

Actual result

Not starting redis server while opening the app/

Expected result

Expected to start redis server while opening the app.

Device: Laptop
Windows: 7 32 bit

Browser: Chrome

Image

![redisserver_1](https://user-images.githubusercontent.com/13567734/51081007-c93fee00-170b-11e9-9b10-f91b44952e3e.jpg)

**Comment by standlove** [comment]
the docker won't start the redis server.
