### ISSUE TITLE
Add and Edit records - Key value is supporting multi-lines

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#343]
![image](https://user-images.githubusercontent.com/42398485/51081438-20ff3a80-16b5-11e9-9a91-2cb9be4972d0.png)

1. Deploy the App and run the application
2. Select a server
3. Click add new record
4. Set Key=ABC (press enter) EFG (Press enter) HIJK; Value Type=String; Value=Test
5. Click Add

**Actual:** Key value is supporting multi-lines

**Expected:** Should not support multi-lies

**Browser(s):** Firefox 64.0.2 (Windows)

**Comment by standlove** [comment]
won't fix.
