### ISSUE TITLE
[$20] command line tool should be moved to middle part of the page

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#35]
### Reproduction Steps ###

1. open the app

2. try to use command line

### Expected Result ###

position of command line tool should be moved to middle part of the page

### Actual Result ###

*See screenshot, it's uncomfortable to use the command line.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![cm](https://user-images.githubusercontent.com/4590317/49596064-6e9ccf00-f9b4-11e8-9f3f-fa14885463f2.jpg)

**Comment by nahidshahin** [comment]
PR https://github.com/topcoderinc/TC-redis-manager/pull/199
