### ISSUE TITLE
Delete branches operation is incorrect

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#363]
![image](https://user-images.githubusercontent.com/42398485/51085745-2e431600-1703-11e9-84a7-0dd270d61b11.png)

1. Deploy the App and run the application
2. Select a server
3. Create a branch - BaicUser:BaicUser1:BaicUser2:BaicUser3:BaicUser4:BaicUser5:BaicUser6:BaicUser7
4. Delete the BaicUser5
5. Click delete branch

Delete Confirmation
Are you sure you want to delete the key "BaicUser:BaicUser1:BaicUser2:BaicUser3:BaicUser4:BaicUser5:"?

**Actual:** All the branches deleted

**Expected:** According to the message above only, should delete BaicUser:BaicUser1:BaicUser2:BaicUser3:BaicUser4:BaicUser5:" that means all the below branches should be deleted but actually system should delete the branches below the selected values

**Browser(s):** Firefox 64.0.2 (Windows)

**Comment by codejamtc** [comment]
Delete Confirmation
Are you sure you want to delete the key "BaicUser:BaicUser1:BaicUser2:BaicUser3:BaicUser4:BaicUser5:"?

Expected: According to the message above should delete BaicUser:BaicUser1:BaicUser2:BaicUser3:BaicUser4:BaicUser5:" that means all the below branches should be retained. But actually system should delete the branches below the selected values not the values above the selected one

**Comment by standlove** [comment]
As I mentioned in the other issues. Branch is a concept in this app, it's not valid for Redis. 

When keys inside the branch are deleted, if the earlier branch has no other keys. The branch won't appear as well.

**Comment by codejamtc** [comment]
@standlove I can see a bug in here clearly. Please check the below video https://www.screencast.com/t/5yrGPnToePy

1. I have BaicUserA:BaicUserB:BaicUserC:BaicUserD:BaicUserE:BaicUserF:BaicUserG:BaicUserH
2. Then I have empty BaicUserD
3. I have a key (Key-C) with BaicUserC
4. I have a key (Key-E) with BaicUserE
5. Then I delete BaicUserD and the message displays: 

Delete Confirmation
Are you sure you want to delete the key **"BaicUserA:BaicUserB:BaicUserC:BaicUserD:"?**

6. But when user click on the YES button, it deletes the BaicUserD to BaicUserH, so the message is wrong in this case or the operation is totally wrong

Please double check
