### ISSUE TITLE
UX - Should disable the save button till use changes the value

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#372]
![image](https://user-images.githubusercontent.com/42398485/51089575-28662880-1735-11e9-8ad5-2b43ca72f7b5.png)

1. Deploy the App and run the application
2. Select a server and select a String Key
3. Click Save

**Actual:** Save button is always enabled

**Expected:** UX - Should disable the save button till use changes the value

**Browser(s):** Chrome 71.0.3578.98 (Windows)

**Comment by standlove** [comment]
won't fix.
