### ISSUE TITLE
Added Successfully message displayed even though there is no item to add

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#373]
![image](https://user-images.githubusercontent.com/42398485/51089966-a842c180-173a-11e9-903a-6321e4b4546d.png)

1. Deploy the App and run the application
2. Create a List
3. Select the list and click add new value
4. Type B
5. Delete the row
6. Click Add

**Actual:** Added Successfully message displayed even though there is no item to add and no items added to the list

**Expected:** Should not display Added Successfully message

**Browser(s):** Chrome 71.0.3578.98 (Windows)

**Comment by codejamtc** [comment]
Happens in all value types: List, Set, Ordered List, **NOT** in Hash Map (it's also incorrect)

https://www.screencast.com/t/8boHfDC4oT

**Comment by standlove** [comment]
should not allow user to delete the last row from the model dialog.

**Comment by sumitdaga** [comment]
this is already fixed by a previous PR!
