### ISSUE TITLE
API Request turns in to {uri: after refreshing

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#375]
![image](https://user-images.githubusercontent.com/42398485/51093374-8fe99b80-1768-11e9-8cea-29aaf0e5bc9f.png)

1. Deploy the App and run the application (Magenta Theme)
2. Import the simple-data-txt
3. Expand the API Request (Last item)
4. Collapse the API Request (Last item)
5. Click refresh

**Actual:** API Request turns in to {uri: after refreshing

**Expected:** It should not happen

**Browser(s):** Chrome 71.0.3578.98 (Windows)

**Comment by standlove** [comment]
won't fix.
