### ISSUE TITLE
[$5] typo should be fixed

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#38]
### Reproduction Steps ###

1. open the app

2. click localhost > global-ordered-list

3. select the first row, click "Delete Key", check modal

### Expected Result ###

Are you sure you want delete select value ?
->
Are you sure you want to delete selected value ?

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![sv1](https://user-images.githubusercontent.com/4590317/49596444-4bbeea80-f9b5-11e8-8f8e-a894b029fcd6.jpg)

Same issue for select multiple rows.

**Comment by winterflame** [comment]
![sv2](https://user-images.githubusercontent.com/4590317/49596494-685b2280-f9b5-11e8-8626-eb3ae9732cac.jpg)

**Comment by phead** [comment]
Hi,

Please check merge request: https://github.com/topcoderinc/TC-redis-manager/pull/140
