### ISSUE TITLE
Toolltip message is not appropriate for delete icon

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#383]
Steps to Reproduce

1. Deploy the app.
2. Make sure that redis server instance is not selected.
3. Hover the mouse over Delete icon.
4. Tooltip says "Remove this Redis server"

Actual Result

Tooltip is not showing appropiate message.

Expected Result

Tooltip to show appropriate message.

Frequency: 
5/5

Device: Laptop
OS: Windows 7 32 bit
Browser: Chrome(latest)

Images

![removetooltip](https://user-images.githubusercontent.com/13567734/51096936-50fa2b00-17e6-11e9-855d-a97d948c8bfd.jpg)

**Comment by standlove** [comment]
it's duplicated with an early issue.
