### ISSUE TITLE
Suggestion to make Help dialog resizable.

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#384]
Steps to Reproduce

1. Deploy the app.
2. Click on the Help icon.
3. Try to resize the Help dialog opened.

Actual Result

Help dialog is not resizable now.

Expected Result

Help dialog to be resizable to be more user friendly.

Frequency
5/5

Device: Laptop
OS: Windows 7 32 bit
Browser: Chrome(latest)

Images

![help_resize](https://user-images.githubusercontent.com/13567734/51097004-e09fd980-17e6-11e9-89a3-2158c9a92e03.jpg)

**Comment by standlove** [comment]
won't fix
