### ISSUE TITLE
Toggle cli panel is not draggable/movable

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#386]
Steps to Reproduce

1. Click on "Toggle cli panel" icon.
2. Try to drag up/down the cli panel.
3. Toggle cli panel is not draggable/movable.

Actual Result

Toggle cli panel is not movable to any location.

Expected Result

Toggle cli panel to be movable to any location.

Frequency
5/5

Device: Laptop
OS: Windows 7 32 bit
Browser: Chrome(Latest)

Images

![togglecli](https://user-images.githubusercontent.com/13567734/51097128-bc90c800-17e7-11e9-8d5a-6b0770598440.jpg)

**Comment by sumitdaga** [comment]
do we need this feature? @standlove

**Comment by standlove** [comment]
no.
