### ISSUE TITLE
Database index is not getting increased/decreased in exponential form

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#389]
Steps to Reproduce

1. Deploy the app.
2.  Click on Add redis server instance icon.
3.  In the dialog give large value for database index. ex.1e+40
4. Try increasing/decreasing the database index.

Actual Result

Database index is not getting increased/decreased in the Add dialog.

Expected Result

Database index to get increased/decreased in the Add dialog.

Frequency
5/5

Device: Laptop
OS: Windows 7 32 bit
Browser: Chrome(latest)

Images

![daabase_index](https://user-images.githubusercontent.com/13567734/51097740-61ad9f80-17ec-11e9-9918-7651b9205e71.jpg)

**Comment by standlove** [comment]
won't fix
