### ISSUE TITLE
[$15] should set max allowed chars for string value

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#39]
### Reproduction Steps ###

1. open the app

2. click localhost > global-ordered-list

3. select a string value to edit, enter super long string for it, observe

### Expected Result ###

should set max allowed chars for string value.
 

### Actual Result ###

*See screenshot, user cannot see the save button if string is too long.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![svv](https://user-images.githubusercontent.com/4590317/49596906-575ee100-f9b6-11e8-9b03-0104464e8fda.jpg)

**Comment by mhikeo** [comment]
Here's the PR: https://github.com/topcoderinc/TC-redis-manager/pull/163
