### ISSUE TITLE
Capitalization of Validation messages  

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#391]
Steps to Reproduce

1. Deploy the app.
2. Open the branch of values stored in server.
3. Try saving a new value for the key.
4. saved successfuly message appears. Its to be capitalized like "Saved Successfully".
5. Similar for other like delete successfully, added successfully etc.

Actual Result

Validation messages were not capitalized.

Expected Result

Validation messages to be capitalized.

Frequency

5/5

Device: Laptop
OS:  Windows 7 32 bit
Browsers: Chrome(latest)

Images

![validation1](https://user-images.githubusercontent.com/13567734/51099411-83ac1f80-17f6-11e9-8126-765755588f1b.jpg)

**Comment by standlove** [comment]
won't fix.
