### ISSUE TITLE
Validation messages to appear consistently same place in the app

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#392]
Steps to Reproduce

1. Deploy the app.
2. Open the branch of values stored in server.
3. Try saving a new value for the key.
4. saved successfuly message appears. Its appear in bottom of app.
5. But "Fail to start redis server message" appears in top page of app.

Actual Result

Validation messages doesn't appear every time same location.

Expected Result

Validation messages to be appeared every time same location.

Frequency

5/5

Device: Laptop
OS:  Windows 7 32 bit
Browsers: Chrome(latest)

Images

**Comment by standlove** [comment]
this is duplicated as well.
