### ISSUE TITLE
Delete set action is not working properly.

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#396]
Steps to Reproduce

1. Deploy the app.
2. Open the branch of values stored in server.
3. Open a set record.
4. Try deleting individual keys by selecting delete icon in the actions column.
5. Delete icon is not user interactive

Actual Result

Delete icon is not user interactive.

Expected Result

Delete icon to be user interactive.

Frequency

5/5

Device: Laptop
OS:  Windows 7 32 bit
Browsers: Chrome(latest), Firefox(latest)

Image

![delete](https://user-images.githubusercontent.com/13567734/51101079-1a7cda00-17ff-11e9-9199-626dcf7da9e5.jpg)

**Comment by standlove** [comment]
cannot reproduce ...
