### ISSUE TITLE
Suggestion to display Multiple select checkbox in top of the set.

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#397]
Steps to Reproduce

1. Deploy the app.
2. Open the branch of values stored in server.
3. Watch the select checkboxes for records.
4. Multiple select checkbox is not there.

Actual Result

Multiple select checkbox is not displayed for the user convenience.

Expected Result

Multiple select checkbox to be displayed for the user convenience.

Frequency

5/5

Device: Laptop
OS:  Windows 7 32 bit
Browsers: Chrome(latest)

Image

![select](https://user-images.githubusercontent.com/13567734/51101196-ad1d7900-17ff-11e9-9c8e-a1197d6892c0.jpg)

**Comment by standlove** [comment]
cannot reproduce. It's already there.
