### ISSUE TITLE
Suggestion to show text near + mark in light theme visible manner

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#398]
Steps to Reproduce

1. Deploy the app.
2. Open the branch of values stored in server.
3. Try add new value for the key.
4. In light theme observe the "Add new value" text in the dialog.
5. Its not visible

Actual Result

Add new value is not visible in light theme.

Expected Result

Add new value to be visible in light theme.

Frequency

5/5

Device: Laptop
OS:  Windows 7 32 bit
Browsers: Chrome(latest)
                 Firefox(latest)

Image

![text](https://user-images.githubusercontent.com/13567734/51101385-76942e00-1800-11e9-8e42-ebbd04ef7aa6.jpg)

**Comment by standlove** [comment]
cannot reproduce. the text is visible for me.
