### ISSUE TITLE
Pagination is not working properly.

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#399]

**Comment by Jacob15** [comment]
Steps to Reproduce

1. Deploy the app.
2. Open the branch of values stored in server.
3.  Items per page dropdown, Page 1 of 8 icons are not user interactive.


Actual Result

Pagination elements is not user interactive.

Expected Result

Pagination elements to be user interactive.

Frequency
5/5

Device: Laptop
OS:  Windows 7 32 bit
Browsers: Chrome(latest)

Images

![pagination](https://user-images.githubusercontent.com/13567734/51101607-5153ef80-1801-11e9-9867-82d4f90d376f.jpg)

**Comment by standlove** [comment]
won't fix
