### ISSUE TITLE
Bug: Node Tree Incorrect

### ISSUE THREAD

**Issue by ksmacleod99** [topcoderinc/TC-redis-manager#4]
![image](https://user-images.githubusercontent.com/28678836/47436328-49d9f880-d774-11e8-986c-649c525f6209.png)
should be:
```API Request
     +-- uri:uri*
              +-- method:GET
                  +-- body:*
                       +-- productTypes:["device","software"]
                             +-- "pageNumber": 5
                                     +-- "anotherKey: anotherValue}```

**Comment by jiangliwu** [comment]
bug from src/app/components/tree-node/tree-node.component.ts line 54
` const regexResults = item.key.match(/[^,{}]+(?=,|{|})(?=,|\{)/g);`

i rewrite it and put it in util.service.ts method splitKey, it should be fixed now, check this MR
https://github.com/topcoderinc/TC-redis-manager/pull/6
