### ISSUE TITLE
Info values were not shown to the user in understandable manner

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#400]
Steps to Reproduce

1. Deploy the app.
2. Open the branch of values stored in server.
3. Enter INFO command in the redis server
4. Server values displayed were not in line by line or in legible to the user.

Actual Result

Server values displayed were not in line by line or in legible to the user.

Expected Result

Server values displayed in the cli panel should be in line by line to the user

Frequency

5/5

Device: Laptop
OS:  Windows 7 32 bit
Browsers: Chrome(latest)

Images

![info](https://user-images.githubusercontent.com/13567734/51101811-48afe900-1802-11e9-9f48-a471648212e8.jpg)

**Comment by standlove** [comment]
this is duplicated with an early reported issue.
