### ISSUE TITLE
Edit dialog box is getting expanded while editing value

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#405]
Steps to Reproduce

1. Deploy the app.
2. Open the branch of values stored in server.
3. Edit a key value.
4. Enter large value for the key.
5. Dialog is getting resized instead of multi line entry getting added.

Actual Result

Dialog getting resized.

Expected Result

Dialog is not getting resized.

Frequency

5/5

Device: Laptop
OS:  Windows 7 32 bit
Browsers: Chrome(latest)

Images

https://www.screencast.com/t/1Cl7ELKbsC

**Comment by sumitdaga** [comment]
this is also now fixed by an earlier fix i think!

**Comment by standlove** [comment]
ok
