### ISSUE TITLE
Edited dialog shows action icons in distorted manner

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#409]
Steps to Reproduce

Follow #405 .

Actual Result

Action icons were showing in distorted manner.

Expected Result

Action icons not to show in distorted manner.

Frequency

5/5

Device: Laptop
OS:  Windows 7 32 bit
Browsers: Chrome(latest)

Images

![edit](https://user-images.githubusercontent.com/13567734/51105473-0e991400-180f-11e9-8431-02b977617dc5.jpg)

**Comment by standlove** [comment]
ok
