### ISSUE TITLE
Nodes are not showing in ascending manner.

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#410]
Steps to Reproduce

1. Deploy the app.
2. Observe the node values
3. Its not in ascending order of data types string, set, has set etc.

Actual Result

Node values is not in ascending order.

Expected Result

Node values to be in ascending order.

Frequency

5/5

Device: Laptop
OS:  Windows 7 32 bit
Browsers: Chrome(latest)

Image

![node](https://user-images.githubusercontent.com/13567734/51106228-25406a80-1811-11e9-900b-14a0e44a0c6e.jpg)

**Comment by sumitdaga** [comment]
i think they are sorted as of now ...can you recheck?

**Comment by standlove** [comment]
yes.
