### ISSUE TITLE
Key name is take large space in the dialog

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#413]
Steps to Reproduce

1. Deploy the app.
2. Add key and value for set with large name.
3. Key name is taking larger space in the modal

Actual Result

Key name is taking larger space in the modal

Expected Result

Key name should not take large space in the modal.

Frequency

5/5

Device: Laptop
OS:  Windows 7 32 bit
Browsers: Chrome(latest)

Images

![key](https://user-images.githubusercontent.com/13567734/51107479-edd3bd00-1814-11e9-8fb1-67fc48f50d3b.jpg)

**Comment by standlove** [comment]
ok
