### ISSUE TITLE
split bar is having one more vertical line

### ISSUE THREAD

**Issue by Jacob15** [topcoderinc/TC-redis-manager#418]
Steps to Reproduce

1. Deploy the app.
2. Drag the split bar.
3. Split bar is having one more line nearer of it.

Actual Result

split bar is having one more line to it.

Expected Result

split bar should not have any line.

Frequency

5/5

Device: Laptop
OS:  Windows 7 32 bit
Browsers: Firefox(latest)
                 Chrome(latest)

Images

![mark](https://user-images.githubusercontent.com/13567734/51108996-d64b0300-1819-11e9-8190-74b01b113d71.jpg)

**Comment by standlove** [comment]
won't fix.
