### ISSUE TITLE
ZRANGE Set10 2 3 is not working

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#425]
![image](https://user-images.githubusercontent.com/42398485/51115243-4c754880-17cd-11e9-8fa6-e13f407540a5.png)

1. Deploy the App and run the application (Magenta Theme)
2. Create some sets with data
3. Expand the CLI
4. Enter ZRANGE Set10 2 3

https://redis.io/commands/zrange

**Actual:** ZRANGE Set10 2 3 is not working

**Expected:** Should return the data between 2 and 3

**Browser(s):** Chrome 71.0.3578.98 (Windows)

**Comment by standlove** [comment]
it only works for ordered set.
