### ISSUE TITLE
ZCARD <Set Name> is not working

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#428]
![image](https://user-images.githubusercontent.com/42398485/51115984-62840880-17cf-11e9-8130-0778ca67f457.png)

1. Deploy the App and run the application (Magenta Theme)
2. Create a List with data https://github.com/topcoderinc/TC-redis-manager/files/2755278/db-1547472272101.zip
3. Expand the CLI
4. Enter ZCARD Set10

https://redis.io/commands/zcard

**Actual:** ZCARD Set10 returns nothing

**Expected:** Should return correct data

**Browser(s):** Chrome 71.0.3578.98 (Windows)

**Comment by standlove** [comment]
this works for me. It only works for ordered-set.
