### ISSUE TITLE
[$15] Table layout is broken if value is too long

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#44]
1. Deploy the App and Open
2. Select an item from the right view
3. Click Add new Records
4. Add a new value (Value Type: Ordered Set)
5. Add value = 	Lorem ipsum dolor sit amet, cu mundi eleifend has, dicunt impedit nonumes vis eaLorem ipsum dolor sit amet, cu mundi eleifend has, dicunt impedit nonumes vis eaLorem ipsum dolor sit amet, cu mundi eleifend has, dicunt impedit nonumes vis eaLorem ipsum dolor sit amet, cu mundi eleifend has, dicunt impedit nonumes vis eaLorem ipsum dolor sit amet, cu mundi eleifend has, dicunt impedit nonumes vis eaLorem ipsum dolor sit amet, cu mundi eleifend has, dicunt impedit nonumes vis ea
6. Click Add

**Actual:** Table layout is broken if value is too long

**Expected:** Should shorten the value if it is too long or should display it in two lines

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/49686508-1f8d9180-fabb-11e8-96b4-8578d6d700c0.png)

**Comment by ksmacleod99** [comment]
see also, #55

**Comment by sumitdaga** [comment]
sorry forgot about this  
PR #212
