### ISSUE TITLE
message should be adjusted when deleting server

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#45]
### Reproduction Steps ###

1. open the app, click the trash icon on left side, observe

### Expected Result ###

Are you sure you want to delete this server?

### Actual Result ###

*See screenshot*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![wt](https://user-images.githubusercontent.com/4590317/49598064-c806fd00-f9b8-11e8-8371-6f264e4f2537.jpg)

**Comment by ksmacleod99** [comment]
Duplicate of #45
