### ISSUE TITLE
[$15]  Can enter spaces for String value while editing

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#49]
1. Deploy the App and Open
2. Select an item from the right view
3. Click Add new Records
4. Add a new value (Value Type: String)
5. Add value = 	String
6. Click Add
7. Select the String value
8. Remove the existing value and add space
9. Click Save
10. Click another value from the list
11. Click String value

**Actual:** Can enter spaces for String value while editing

**Expected:** If user enters space as a string while editing, should display a validation

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/49686610-88c1d480-fabc-11e8-99d5-6726356891cf.png)

**Comment by ksmacleod99** [comment]
hey there @o-kaya there are some merge conflicts on your PR. It looks like a rebase might fix it. Could you please investigate?
