### ISSUE TITLE
Feature Request: Themes

### ISSUE THREAD

**Issue by ksmacleod99** [topcoderinc/TC-redis-manager#5]
Client Requests: 

- Setup a theme file (Angular material) so that we can add more than one theme. 
- Add  the ability to switch themes in the settings

**Comment by jiangliwu** [comment]
function added in this MR #6 , please follow this steps to add new theme

1. add a theme named 'test' in src/app/theme-config.ts (THEMES array)
2. copy src/themes/dark-theme.scss to src/themes/test-theme.scss and update colors and make sure the last style name to .test-theme
3. import test-theme.scss in src/styles.scss

4. open redis-manager tool and click settings button, then switch theme to `test`
