### ISSUE TITLE
no need to shown Index column

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#51]
### Reproduction Steps ###

1. open the app

2. expand all items on left

3. click on "global-ordered-list" of "default-local"

4. observe the main table, try to delete one row, observe

### Expected Result ###

No need to shown Index column.

### Actual Result ###

*See screenshot, Index is simply the row count.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![rc](https://user-images.githubusercontent.com/4590317/49599269-87f54980-f9bb-11e8-91eb-23974d0a4466.jpg)

**Comment by ksmacleod99** [comment]
You're right, but we'll see if the client has any desire to keep it (especially if we add a sorting feature)

**Comment by standlove** [comment]
it's used for the ordered list.
