### ISSUE TITLE
[$10] value should be trimmed for saving

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#52]
### Reproduction Steps ###

1. open the app

2. add a new key/value, enter "key" as key, and "test" as the value.

3. edit the value to "       test    ", save that

### Expected Result ###

Value should be trimmed for saving

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

![trim](https://user-images.githubusercontent.com/4590317/49626338-5492d900-fa14-11e8-9e1a-7c261675a71b.jpg)

**Comment by nahidshahin** [comment]
PR https://github.com/topcoderinc/TC-redis-manager/pull/167
