### ISSUE TITLE
[$10] Can't click on Add new value

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#53]
1. Deploy the App and Open
2. Select an item from the right view
3. Click Add new Records
4. Add a new value (Value Type: Hash Map)
5. Add some values
6. Select few items
7. Click edit
8. Click add new value

**Actual:** Can't click on Add new value

**Expected:** Should be able to click on add new value button

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/49686619-9ecf9500-fabc-11e8-8e83-e5e1b36901fe.png)

**Comment by mhikeo** [comment]
@ksmacleod99 This is fixed in PR: 
https://github.com/topcoderinc/TC-redis-manager/pull/195
