### ISSUE TITLE
[$10] Validation message is shown after closing the edit value form

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#54]
1. Deploy the App and Open
2. Select an item from the right view
3. Click Add new Records
4. Add a new value (Value Type: Hash Map)
5. Add six values
6. Select All items
7. Click edit
8. Replace a value with space
9. Click update
10. Click Cancel

**Actual:** Validation message is shown after closing the edit value form

**Expected:** Should not show the validation message after closing the form

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/49686633-d1798d80-fabc-11e8-8f37-54184e0b0085.png)

**Comment by nahidshahin** [comment]
@ksmacleod99 I guess the problem has fixed by earlier commits. Found just one error that I reported to the author https://github.com/topcoderinc/TC-redis-manager/issues/104#issuecomment-450483655

**Comment by ksmacleod99** [comment]
thank you! I will close this issue then.
