### ISSUE TITLE
Long record names are not adjusted to the section width

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#55]
1. Deploy the App and Open
2. Select an item from the right view
3. Click Add new Records
4. Add a new value (Value Type: Hash Map)
5. Add a long Key name
6. Click Add
7. Check the long name inside the expandable list

**Actual:** If the record name is too long it is not displaying the full content

**Expected:** Should limit the number of characters shown and display the total number of items visible

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/49686827-0d622200-fac0-11e8-9ce0-aaad9561bbef.png)

**Comment by ksmacleod99** [comment]
this isn't a true duplicate; if #44 is fixed, hopefully this one will be too.

**Comment by iversonLv** [comment]
I don't see the issues, maybe it is the index text too close to the checkbox?
![image](https://user-images.githubusercontent.com/4952611/50377408-d8290880-0657-11e9-82a1-f68e08dc717f.png)
