### ISSUE TITLE
[$25] added servers are not persisted in different browsers

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#57]
### Reproduction Steps ###

1. open http://localhost:3003/ in Firefox, then add 2 redis servers

2. open http://localhost:3003/ in Chrome, observe

### Expected Result ###

There should be 3 redis servers in Chrome, just like in Firefox.

### Actual Result ###

*See screenshots.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![ff](https://user-images.githubusercontent.com/4590317/49622615-44273200-fa05-11e8-87fc-6588b56d1177.jpg)


![chrome](https://user-images.githubusercontent.com/4590317/49622617-48ebe600-fa05-11e8-9a73-51ba2f58144f.jpg)

**Comment by nahidshahin** [comment]
@ksmacleod99 currently servers are saved at browsers local storage. That's why changing browser can't load different browser's saved state. 

To load in different browsers, we need to persist in Database. Now the question is which database to use to store?

**Comment by ksmacleod99** [comment]
Thanks for pointing this out. This is something I'll have to ask the client about, depending on how they plan on using this app in production.
