### ISSUE TITLE
[$5] "Database" should be changed to "Database Index" in the error message

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#58]
### Reproduction Steps ###

1. open app, click to add new server

2. enter 17 as Database Index, click to save

### Expected Result ###

"Datebase" should be changed to "Database Index" in the error message

### Actual Result ###

*See screenshots.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![di](https://user-images.githubusercontent.com/4590317/49622958-a92f5780-fa06-11e8-9d98-48107e746d46.jpg)

**Comment by phead** [comment]
Hi,

Please check this : https://github.com/topcoderinc/TC-redis-manager/pull/144
