### ISSUE TITLE
[$15]  should not allow enter non integer as Database Index

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#59]
### Reproduction Steps ###

1. open app, click to add new server

2. enter a string like "afdsaf" as Database Index, click to save

### Expected Result ###

Should not save successfully.

### Actual Result ###

*See screenshots, Database Index is saved as "NaN".*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![char](https://user-images.githubusercontent.com/4590317/49623068-07f4d100-fa07-11e8-909b-0342d1c6ba42.jpg)

![nan](https://user-images.githubusercontent.com/4590317/49623079-14792980-fa07-11e8-8cbf-4217d4abbf40.jpg)

**Comment by phead** [comment]
Hi,
Please check this mr: https://github.com/topcoderinc/TC-redis-manager/pull/182
