### ISSUE TITLE
Only delete button is displayed

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#60]
1. Deploy the App and Open
2. Select an item from the right view (Hash Map)
3. Click Add new Records
4. Click + Add new value 3 times
5. Click Add
6. Click + Add new value

**Actual:** Click on the add new value display delete button without key and value fields

**Expected:** Should display key and value fields

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by ksmacleod99** [comment]
unable to duplicate
