### ISSUE TITLE
[$20] it still shows delete confirmation popup even though no server is selected

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#61]
### Reproduction Steps ###

1. open app, click to add a new server

2. select the newly added server, click Trash icon to delete, proceed to delete 

3. then click the Trash icon again, observe

### Expected Result ###

Should not show confirmation popup since no server is selected in this case.

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![se](https://user-images.githubusercontent.com/4590317/49623724-b732a780-fa09-11e8-850e-a66f88bb9044.jpg)

**Comment by phead** [comment]
Hi,

Please check mr: https://github.com/topcoderinc/TC-redis-manager/pull/176

**Comment by phead** [comment]
Hi, @ksmacleod99 

Is this fix accepted?  I found associated MR has been merged.

**Comment by ksmacleod99** [comment]
Hi @phead yes it's accepted. It was included in your payment :) I'm just going through now and making sure I closed everything out (apparently I didn't). Thank you!
