### ISSUE TITLE
[$10] the trash icon remains selected state if we dismiss the confirmation modal

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#62]
### Reproduction Steps ###

1. open app, click to add a new server

2. select the newly added server, click Trash icon to delete, proceed to delete 

3. then click the Trash icon again, click NO on the modal, observe the Trash icon

### Expected Result ###

Should not be in selected state anymore.

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![ti](https://user-images.githubusercontent.com/4590317/49624165-5906c400-fa0b-11e8-8eb7-01a0e123aecf.jpg)

**Comment by sjbr** [comment]
This is duplicate issue was fixed for:

https://github.com/topcoderinc/TC-redis-manager/issues/85

**Comment by sjbr** [comment]
fixed in pull request:
https://github.com/topcoderinc/TC-redis-manager/pull/175
