### ISSUE TITLE
[$25] should not allow add server with same name

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#63]
### Reproduction Steps ###

1. open app

2. click to add a new server, click Add

3. repeat step 2 several times

### Expected Result ###

Should not allow add server with same name.

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![same](https://user-images.githubusercontent.com/4590317/49624232-a1be7d00-fa0b-11e8-8579-09d5b2e65986.jpg)

**Comment by mhikeo** [comment]
Here's the PR: https://github.com/topcoderinc/TC-redis-manager/pull/170
