### ISSUE TITLE
Save button is hidden, if string is too long

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#64]
1. Deploy the App and Open
2. Select an item from the right view (String)
3. Add a long string value

**Actual:** Save button is hidden, if string is too long

**Expected:** Long string value should have scroll bars to scroll the content

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/49686845-3e425700-fac0-11e8-940d-f1461e056b74.png)

**Comment by ksmacleod99** [comment]
duplicate of #39
