### ISSUE TITLE
[$20] pagination and Items per page should be removed if current table does not have such functionality

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#66]
### Reproduction Steps ###

1. open app

2. click default-local , observe

### Expected Result ###

Pagination and Items per page should be removed if current table does not have such functionality.

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![page](https://user-images.githubusercontent.com/4590317/49624675-586f2d00-fa0d-11e8-95a0-4144d4b0ebb5.jpg)

**Comment by mhikeo** [comment]
@ksmacleod99 Kindly assign this to me. I'm unable to assign it myself. Thanks.

**Comment by phead** [comment]
Hi, 
Please check the mr: https://github.com/topcoderinc/TC-redis-manager/pull/178

only 'zset', 'set' and 'hash' type contains pagination function.
