### ISSUE TITLE
[common] scrolling issue

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#67]
### Reproduction Steps ###

1. open app

2. click default-local , try to scroll down, observe

### Expected Result ###
should be able to scroll down to view more data.

### Actual Result ###

*See screenshot, cannot scroll.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![scrol](https://user-images.githubusercontent.com/4590317/49624774-c9aee000-fa0d-11e8-87bd-c5be2435526b.jpg)

**Comment by ksmacleod99** [comment]
duplicate of #28
