### ISSUE TITLE
[$5] spelling issues on dashboard

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#69]
### Reproduction Steps ###

1. open app

### Expected Result ###
1) No redis instance selected
2) Please select a redis instance to enter redis command

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![sp](https://user-images.githubusercontent.com/4590317/49625777-de8d7280-fa11-11e8-9379-bf8fef557d95.jpg)

**Comment by Schpotsky** [comment]
check fix #149
