### ISSUE TITLE
[$15] Can input 0 to Ordered Set score

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#70]
1. Deploy the App and Open
2. Select an item from the right view (Ordered Set)
3. Click Add new value
4. Enter value name
5. Add Score=0
6. Click Add
7. Click Add new value
8. Enter value name
9. Click Add

**Actual:** Can input 0 to Ordered Set score

**Expected:** Should validate the input = 0

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/49686857-692cab00-fac0-11e8-8234-479c7fc8a3e3.png)

**Comment by JDK88** [comment]
Do you mean we cannot enter duplicate key 'name' ?

**Comment by JDK88** [comment]
Or you just need show Error Message:"Score cannot be 0"
when score is 0 ? @codejamtc

**Comment by ksmacleod99** [comment]
hey @JDK88 we really do need to keep the ability to enter '0', since it is valid in Redis. I'm sorry I didn't catch this earlier. Thank you for your work and your MR, but I won't be able to merge it and need to close this issue. You can email me or ping me on slack if you have questions :)

**Comment by JDK88** [comment]
"I see, you mean , when I input the 0, the behavior is correct(show error msg)
but, if I do not input the 0, the default value will be 0, and do not show error msg(This behavior is not correct)"
So, what about the 6th. step ??
I think there should be the same result in Step 6 and Step 9.
If 0 can be input, then error msg should not be displayed in Step6.
If 0 cannot be input, then error msg shoud be displayed in Step 9.
1.Deploy the App and Open
2.Select an item from the right view (Ordered Set)
3.Click Add new value
4.Enter value name
5.Add Score=0
6.Click Add
7.Click Add new value
8.Enter value name
9.Click Add

@ksmacleod99
