### ISSUE TITLE
[$10] Tool Tip - Hover on Edit button, tool tip is not visible

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#74]
1. Deploy the App and Open
2. Select an item from the right view (Hash Map)
3. Hover over Edit button

**Actual:** Hover on Edit button, tool tip is not visible. But scroll the list once and hover over the edit button of the first item visible

**Expected:** Should show the Tool tip - Edit this item

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/49686868-9711ef80-fac0-11e8-9364-b4bbbbe582ed.png)

**Comment by iversonLv** [comment]
#74 and #75 are same issues I raise one pr #161
