### ISSUE TITLE
[$10] Tool Tip - Hover Delete button, tool tip is not visible

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#75]
1. Deploy the App and Open
2. Select an item from the right view (Hash Map)
3. Hover over Delete button

**Actual:** Hover on Delete button, tool tip is not visible. But scroll the list once and hover over the Delete button of the first item visible

**Expected:** Should show the Tool tip - Delete forever

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/49686870-9da06700-fac0-11e8-84bb-e813dd77b46d.png)

**Comment by iversonLv** [comment]
#74 and #75 are same issues I raise one pr #161
