### ISSUE TITLE
[$20] no error message shown if intended to add duplicate keys for HashMap

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#77]
### Reproduction Steps ###

1. open app

2. select default-local,

3. click Add new Records, select Value Type as Hash Map

4. on the 1st line, enter "testKey" for Key

5. add one more row, enter "a" / "b" for each row, click Add

### Expected Result ###
should show validation error when there are duplicate keys.

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![k](https://user-images.githubusercontent.com/4590317/49626700-11396a00-fa16-11e8-90a5-73f4894252bc.jpg)

**Comment by ksmacleod99** [comment]
hey there @mhikeo I am still able to add duplicate keys; it accepts the most recently added one.
