### ISSUE TITLE
[$20] no error message shown if intended to add duplicate values for Set

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#78]
### Reproduction Steps ###

1. open app

2. select default-local

3. click Add new Records, select Value Type as Set

4. add more rows, with duplicate values, click Add

### Expected Result ###
should show validation error when there are duplicate values.

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![set](https://user-images.githubusercontent.com/4590317/49626797-53fb4200-fa16-11e8-8578-32b9be510d26.jpg)

**Comment by ksmacleod99** [comment]
Hi @mhikeo I am able to add duplicate values to this one as well.
