### ISSUE TITLE
[$20] validation error message is incorrect for Ordered Set if we enter non integer for Score

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#79]
### Reproduction Steps ###

1. open app

2. select default-local

3. click Add new Records, select Value Type as Ordered Set

4. add more rows, enter random text for key, with some non integer values for score, click Add, observe

### Expected Result ###
validation error message should be accurate for Ordered Set if we enter non integer for Score.

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

**Comment by winterflame** [comment]
![err](https://user-images.githubusercontent.com/4590317/49626926-0d5a1780-fa17-11e8-91b3-cc73ea906841.jpg)

**Comment by mhikeo** [comment]
@ksmacleod99 For the fix, instead of putting a validation, I just forced the field to only allow numeric.
