### ISSUE TITLE
All Locations - Pagination record count is not increasing

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#80]
1. Deploy the App and Open
2. Select an item from the right view
3. Click Add new Records
4. Add a new value (Value Type: Hash Map)
5. Add some values
6. Click Add new value
7. Add another value

**Actual:** Pagination record count is not increasing

**Expected:** Should increase the record count in the pagination area

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/49686899-f53ed280-fac0-11e8-844c-653f4f810476.png)

**Comment by ksmacleod99** [comment]
Related to #18, possibly same issue but I am going to keep this one open since it describes the problem differently.
