### ISSUE TITLE
[$5] modal title is inconsistent with the text of the clicked button 

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#82]
### Reproduction Steps ###

1. open app

2. select default-local

3. click Add new Records, observe the modal title

### Expected Result ###
Should make button text and modal title consistent.

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Firefox 63.0.3 (64-bit)*

![add](https://user-images.githubusercontent.com/4590317/49633423-3f2da700-fa34-11e8-87e2-eec66fe6dc5f.jpg)

**Comment by phead** [comment]
Hi,

Please check https://github.com/topcoderinc/TC-redis-manager/pull/143
