### ISSUE TITLE
[$30] No docker file to build

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#84]
### Reproduction Steps ###

1. open README.md , try to use docker to build the app

2. observe

### Expected Result ###

1) There should be a build-docker-image.sh like it mentioned.

2) dokcer -> docker

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Google Chrome Version 71.0.3578.80 (Official Build) (64-bit)*

![readme](https://user-images.githubusercontent.com/4590317/49684204-88045f00-fb0b-11e8-8f42-603ddb62cef3.jpg)

**Comment by nahidshahin** [comment]
PR https://github.com/topcoderinc/TC-redis-manager/pull/204
