### ISSUE TITLE
(common) icon for adjusting the number value is too small

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#87]
### Reproduction Steps ###

1. open the app

2. select default-local, expand all items on left

3. click Add new Records, select Value Type as Ordered Set

4. focus the Score field, observe

### Expected Result ###

icon should be bigger so that it's easier to click.

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Google Chrome Version 71.0.3578.80 (Official Build) (64-bit)*

**Comment by winterflame** [comment]
![icon](https://user-images.githubusercontent.com/4590317/49684915-7de75e00-fb15-11e8-8954-a9c3c9ead055.jpg)

**Comment by standlove** [comment]
won't fix.
