### ISSUE TITLE
found some vulnerabilities when building

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#9]
1. execute `npm i`, observe console

expected: no vulnerabilities

actual: see screenshot

**Comment by winterflame** [comment]
![1](https://user-images.githubusercontent.com/4590317/49591865-95ee9e80-f9aa-11e8-8304-12fb59bdd8c0.jpg)

**Comment by SaSanju** [comment]
tcx_Assigned

**Comment by standlove** [comment]
won't fix.
