### ISSUE TITLE
[$15] error message should be changed when no redis instance selected

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#91]
### Reproduction Steps ###

1. open the app

2. click the Trash icon, observe

### Expected Result ###
You need to select Redis instance first.

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Google Chrome Version 71.0.3578.80 (Official Build) (64-bit)*

**Comment by ksmacleod99** [comment]
Related to #108

**Comment by phead** [comment]
HI, 
Please check mr:  https://github.com/topcoderinc/TC-redis-manager/pull/177
