### ISSUE TITLE
[$5] modal title is inconsistent with the button text

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#95]
### Reproduction Steps ###

1. open the app

2. select "default-localhost", click on "global-ordered-list"

3. click Add new Value button, observe the modal

### Expected Result ###

"Add new Value" should be consistent with "Add new value".

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Google Chrome Version 71.0.3578.80 (Official Build) (64-bit)*

![sp](https://user-images.githubusercontent.com/4590317/49686189-dde8ff00-fb2b-11e8-8b94-e3903747b7e2.jpg)

**Comment by Schpotsky** [comment]
Check PR #139
