### ISSUE TITLE
[$15] All Locations - Checkbox selection is not visible

### ISSUE THREAD

**Issue by codejamtc** [topcoderinc/TC-redis-manager#96]
![image](https://user-images.githubusercontent.com/42398485/49686385-61b5d380-fab9-11e8-9cda-58cdaa2ae70f.png)

1. Deploy the App and Open
2. Select an item from the right view (Hash Map) or Any
3. Select an item

**Actual:** When user selects a checkbox from the table, it is not clear in white theme

**Expected:** Should use the purple color for selected checkbox

**Browser(s):** Firefox 63.0.3 (Windows)

**Comment by ksmacleod99** [comment]
recommendation: #a3aee0
