### ISSUE TITLE
[$10] text color changed after clicking on the modal

### ISSUE THREAD

**Issue by winterflame** [topcoderinc/TC-redis-manager#99]
### Reproduction Steps ###

1. open the app

2. click Settings icon

3. select dark as theme, observe

4. click on the Settings modal, observe

### Expected Result ###

Text color should be constent.

### Actual Result ###

*See screenshots.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14*

Browser: *Google Chrome Version 71.0.3578.80 (Official Build) (64-bit)*

**Comment by winterflame** [comment]
![d1](https://user-images.githubusercontent.com/4590317/49686535-db3cd880-fb30-11e8-9146-a6cec598a221.jpg)

![d2](https://user-images.githubusercontent.com/4590317/49686536-db3cd880-fb30-11e8-8deb-9c0d34c48c2f.jpg)

**Comment by devansdev** [comment]
this seems to be happen in all forms, for now I will apply the fix for this form, if request to apply the fix for all forms, will change it to apply it globally
